---
- name: Configure macOS
  hosts: localhost
  connection: local
  become: false

  roles:
    - role: homebrew
      tags: [homebrew]

    - role: macos-update
      tags: [update]

    - role: macos-defaults
      tags: [defaults]

    - role: common
      tags: [directories]

    - role: mac-dotfiles
      tags: [macdot]

    - role: packages-base
      tags: [packages]
