---
- name: Configure macOS
  hosts: localhost
  connection: local
  become: false

  roles:
    - role: macos-defaults
      tags: [defaults]

    - role: common
      tags: [directories]

    - role: packages-base
      tags: [packages]
