---
user: sn0w
timezone: Europe/Vienna

home_directories:
  - Projects
  - Downloads
  - Documents
  - Pictures/Wallpapers
  - Pictures/Screenshots
  - Pictures/Icons
  - Music
  - Videos
  - Public
  - Templates
  - Desktop
