---
- name: Update sudoers to allow passwordless softwareupdate
  ansible.builtin.copy:
    dest: /etc/sudoers.d/softwareupdate
    content: |
      {{ ansible_facts['user_id'] }} ALL=(ALL) NOPASSWD: /usr/sbin/softwareupdate
    mode: "0440"
    validate: visudo -cf %s
  become: true
  tags:
    - sudo
