---
ansible_connection: local
ansible_become_pass: "{{ vault_become_pass | default(omit) }}"

homebrew_formulas_extra:
  - openconnect

homebrew_casks:
  - zen-browser
  - nordvpn
  - lulu
  - raycast
  - arc
  - nikitabobko/tap/aerospace
  - ubersicht
  - caffeine
  - displaylink
  - hammerspoon
  - telegram
  - whatsapp
  - iina
  - localsend
  - antigravity
  - theboredteam/boring-notch/boring-notch
  - balenaetcher
  - utm
  - kitty
  - autodesk-fusion
  - affinity
