---
ansible_connection: local
ansible_become_pass: "{{ vault_become_pass | default(omit) }}"

shared_packages:
  - zsh
  - tree
  - git
  - gh
  - neovim
  - tmux
  - fastfetch
  - jq
  - btop
  - bat
  - eza
  - ripgrep
  - fd
  - starship
  - fzf
  - git-delta
  - python3
  - ansible

homebrew_casks:
  - zen-browser
  - nordvpn
  - lulu
  - appcleaner
  - hiddenbar
  - raycast
  - arc
  - nikitabobko/tap/aerospace
  - ubersicht
  - caffeine
  - displaylink
  - hammerspoon
  - telegram
  - whatsapp
  - iina
  - localsend
  - antigravity
  - theboredteam/boring-notch/boring-notch
  - balenaetcher
  - utm
  - kitty
  - autodesk-fusion
  - affinity
